package assistant.common;

public enum ErrorCode {
    VALIDATION_ERROR,
    NOT_FOUND,
    STATE_CONFLICT,
    SCHEDULE_CONFLICT,
    AI_NOT_CONFIGURED,
    AI_AUTH_FAILED,
    AI_RATE_LIMITED,
    AI_TIMEOUT,
    AI_BAD_REQUEST,
    AI_REMOTE_UNAVAILABLE,
    AI_NETWORK_ERROR,
    AI_EMPTY_RESPONSE,
    AI_MALFORMED_RESPONSE,
    SYSTEM_ERROR
}
